server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://registry-deploy-itwiclrlua-uc.a.run.app/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicesbc-service
          uri: lb://servicesbc-service
          predicates:
            - Path=/services/**
        - id: userprofile-service
          uri: lb://userprofile-service
          predicates:
            - Path=/users/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**
        - id: qualification-service
            uri: lb://qualification-service
            predicates:
              - Path=/qualifications/**
