server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: https://registry-deploy-itwiclrlua-uc.a.run.app/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicesbc-service
          uri: https://6ed6eqqrcp.us-east-2.awsapprunner.com
          predicates:
            - Path=/services/**
        - id: subscription-service
          uri: https://subscription-service-deploy-6ndum5nuxa-uc.a.run.app
          predicates:
            - Path=/subscriptions/**
        - id: qualification-service
          uri: https://terasoftapp.azurewebsites.net
          predicates:
            - Path=/qualifications/**
        - id: userprofile-service
          uri: lb://userprofile-service
            - Path=/users/**